[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'joshdick/onedark.vim'
hook_add = '''
  colorscheme onedark
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
  set signcolumn=yes
  set updatetime=1000
  nnoremap [gitgutter] <Nop>
  nmap <C-g> [gitgutter]
  nmap [gitgutter]j <Plug>(GitGutterNextHunk)
  nmap [gitgutter]k <Plug>(GitGutterPrevHunk)
  nmap [gitgutter]u <Plug>(GitGutterUndoHunk)
'''

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = '''
  command Gst :Gstatus
  command Gdf :Gdiff
  command Gbl :Gblame
'''

[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_add = '''
  nmap n <Plug>(anzu-n-with-echo)
  nmap N <Plug>(anzu-N-with-echo)
  nmap * <Plug>(anzu-star)
  nmap # <Plug>(anzu-sharp)
'''

[[plugins]]
repo = 'godlygeek/tabular'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'Xuyuanp/nerdtree-git-plugin'
hook_add = '''
let g:NERDTreeIndicatorMapCustom = {
	\ "Modified"  : "*",
	\ "Staged"    : "+",
	\ "Untracked" : "|",
	\ "Renamed"   : "@",
	\ "Unmerged"  : "=",
	\ "Deleted"   : "-",
	\ "Dirty"     : "!",
	\ "Clean"     : "^",
	\ "Ignored"   : "_",
	\ "Unknown"   : "?"
\ }
'''

[[plugins]]
repo = 'esnme/ultrajson'

[[plugins]]
repo = 'kana/vim-gf-diff'

[[plugins]]
repo = 'kana/vim-gf-user'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'kshenoy/vim-signature'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'
 
###fzf.vim
[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'Yggdroot/indentLine'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#buffer_idx_mode = 1
nmap <C-j> <Plug>AirlineSelectPrevTab
nmap <C-k> <Plug>AirlineSelectNextTab
'''
[[plugins]]
repo = 'vim-airline/vim-airline-themes'
hook_add = '''
let g:airline_theme='deus'
'''

[[plugins]]
repo = 't9md/vim-quickhl'
hook_add = '''
nmap <Space>m <Plug>(quickhl-manual-this)
xmap <Space>m <Plug>(quickhl-manual-this)
nmap <Space>M <Plug>(quickhl-manual-reset)
xmap <Space>M <Plug>(quickhl-manual-reset)
nmap <Space>/ <Plug>(quickhl-cword-toggle)
'''

[[plugins]]
repo = 'kazuph/previm'
rev = 'feature/add-plantuml-plugin'
hook_add = '''
let g:previm_open_cmd="google-chrome"
'''
