#!/bin/bash
cd $HOME/.vim
git pull
git submodule foreach git pull
git submodule init
git submodule update
git commit -a -m 'update all vim plugins'
# syntax
cd $VIM_HOME/syntax
wget https://raw.githubusercontent.com/aklt/plantuml-syntax/master/syntax/plantuml.vim
